### ISSUE TITLE
Dashboards & 2FA

### ISSUE THREAD

**Issue by majortomts** [timed-and-secured-assets/formr.org#10]
- Nutzerollen-Dashboards
- 2FA

**Comment by majortomts** [comment]
Depends on #9

**Comment by ThatsEli** [comment]
We fixed the Ui for the user deletion and added the functionality;

Also we started working on the 2FA codes (We chose a php library that is suitable regarding the licence and compatibility and included it in the project via composer(and changed the dockerfile to make sure the deps are installed and kept up-to-date))

**Comment by ThatsEli** [comment]
Okay, I added 
- a 2FA check for login (Exta page in login flow, only when 2fa is enabled)
- 2FA setup in user dashboard including
   - QR code for easy importing into apps e.g. Microsoft/Google authenticator
   - code confirmation that ensures the user has the secret storec locally

**Comment by Epd02** [comment]
I created the backend for the 2FA codes

- the 'survey_users' table now has a new '2fa_code' column with a default value of ''
- we can check if the user has 2FA set up by checking if '2fa_code' is equal to ''
- when the user sets up 2FA the secret is written into the database
- when logging in using 2FA, the entered code is checked against the secret in the database
- added functions in user.php for getting and setting the 2fa_code and for checking if 2fa is set up

We still need to implement something to allow users to disable 2FA again. Currently they can also set up 2FA again, overriding the secret in the database. This is controversial, but currently desired.
We should possibly also add backup codes

**Comment by ThatsEli** [comment]
I've implemented a few new functions:

- Added a new page to inform users that they must disable their existing 2FA secret before creating or generating a new one
- This page now includes a verification process for disabling the current secret. Users need to enter a valid code to proceed
- Upon successful verification, the current secret is deleted, enabling users to generate anew one via the setup flow
- Enhanced the information stored in the QR code for a better UX. The 2FA app will now display the account and issuer details correctly

**Comment by ThatsEli** [comment]
We now have 2FA backup codes

- the 'survey_users' table now has a backup_codes field that contains the 10 backup codes
- generates new codes on 2fa setup, stores them into the db and shows them to the user **once**
- validates if the entered code is a backup code before checking the entered code with the secret in the db
  - if a backup code is used, the code gets removed from the db (one time use! -> regnerate with new 2fa setup)

This should complete all the 2FA features!

**Comment by ThatsEli** [comment]
I propose to seperate the user-dashbaords and 2FA as there are currently no changes regarding user levels and we depend on those for further development. If we seperate the two parts, we can merge the 2FA code.
