### ISSUE TITLE
Wasserzeichen

### ISSUE THREAD

**Issue by majortomts** [timed-and-secured-assets/formr.org#6]
- Robuste Wasserzeichen in Python
- Screenshot-Resistenz
- Grayscale-Bild oder QR-Code einbetten

**Comment by majortomts** [comment]
PHP LSB Steganographie in image-watermarking/php

**Comment by majortomts** [comment]
Aktuelle Entwicklung robuster Wasserzeichen in Python in image-watermarking/python

**Comment by majortomts** [comment]
QR-Code z.B. "Eigentümer Uni Münster"

**Comment by tobiasjutzi** [comment]
Für Sichtbare Wasserzeichen: Auswahlmenü beim Ersteller der Umfrage

**Comment by majortomts** [comment]
Robuste Verfahren für Wasserzeichen sind in Python implementiert. Folgende To-Dos sind offen:

- [ ] QR-Code Generation und Einbettung als Wasserzeichen (Aktuell in Arbeit)
- [ ] Command Line Interface (Aktuell in Arbeit)
- [ ] Integration in formr (PHP)
- [ ] (Optional: Fine-Tuning der Parameter für die Einbettung der Wasserzeichen)

**Comment by majortomts** [comment]
Entwurf für die Nutzung des CLI zum Einbetten von Wasserzeichen:

`usage: main.py embed [-h] -i IMAGE_PATH [-o OUTPUT_PATH] [-w WATERMARK] -m METHOD

options:
  -h, --help            show this help message and exit
  -i IMAGE_PATH, --image_path IMAGE_PATH
                        path to the image to add the watermark to
  -o OUTPUT_PATH, --output_path OUTPUT_PATH
                        path where to save the watermarked image to
  -w WATERMARK, --watermark WATERMARK
                        watermark text to embed in the image
  -m METHOD, --method METHOD
                        method to use for the embedding

output:
  on exit code 0:
    0: WATERMARKED_IMAGE_PATH
    1: method-specific output (serialized array|int)
  on exit code 1:
    0: error message (possibly multiple lines)`

**Comment by ThatsEli** [comment]
I am going to implement the concrete php implementation/usage of the cli in the`watermark` branch.

**Comment by ThatsEli** [comment]
Okay, we now have
- the python CLI is now implemented in PHP
- i've added UI settings for selecting the watermarking method and content
- the survey_runs table now has "watermark_method" and "watermark_content" fields
- the run settings are now properly saving those details to the database
- formr now triggers the python CLI based on the selected watermarking settings when an image is uploaded
- additional matrix data, essential for invisible watermarking, is stored alongside the image in an accompanying file
